<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<!-- Bootstrap -->
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<title>session_22</title>
</head>

<body>
	<h4 class=" display-4 text-center my-4 text-primary">Asynchronous JavaScript 2 - Catch Method</h4>

	<script>
		// .catch() is for handling errors in Promises.
		// It helps keep asynchronous code clean and readable.
		// Itâ€™s equivalent to the catch block in try...catch, but used in a Promise chain.

		const fetchData = (shouldFail) => {
			return new Promise((resolve, reject) => {
				setTimeout(() => {
					if(shouldFail) {
						reject("Error: Failed To Fetch Data.");
					} else {
						resolve("Data Fetched Successfully!");
					}
				}, 1000);
			});
		};

		fetchData(true)
		.then(data => {
			console.log(data);
		})
		.catch(error => {
			console.error("Caught:", error)
		});
	</script>
</body>

</html>